"use strict";
const dropZone=document.getElementById("drop-zone"),fileNameEl=document.getElementById("file-name"),btnPick=document.getElementById("btn-pick"),btnInject=document.getElementById("btn-inject"),frame=document.getElementById("p2r3-frame"),overlay=document.getElementById("overlay"),overlayMsg=document.getElementById("overlay-msg"),frameErr=document.getElementById("frame-err"),errDetail=document.getElementById("err-detail"),btnRetry=document.getElementById("btn-retry"),sDot=document.getElementById("s-dot"),sMsg=document.getElementById("s-msg");
let stagedFile=null,contentReady=false;
function setStatus(s,t){sDot.className=s;sMsg.className=s;sMsg.textContent=t}
function inferMime(n){const e=n.split(".").pop().toLowerCase();return({pdf:"application/pdf",epub:"application/epub+zip",mobi:"application/x-mobipocket-ebook",azw:"application/vnd.amazon.ebook",azw3:"application/vnd.amazon.ebook",txt:"text/plain",html:"text/html",htm:"text/html",doc:"application/msword",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",rtf:"application/rtf",odt:"application/vnd.oasis.opendocument.text",cbz:"application/vnd.comicbook+zip",cbr:"application/vnd.comicbook-rar",fb2:"application/x-fictionbook+xml",djvu:"image/vnd.djvu"})[e]??"application/octet-stream"}
function stageFile(d,n,t){stagedFile={fileData:d,fileName:n,fileType:t};fileNameEl.textContent="✔ "+n;fileNameEl.classList.add("on");dropZone.classList.add("has-file");btnInject.disabled=false;setStatus("ok","Ready: "+n+" — click ⬇ Inject")}
async function pickWithFSA(){try{const[h]=await window.showOpenFilePicker({multiple:false});const f=await h.getFile();const b=await f.arrayBuffer();stageFile(new Uint8Array(b),f.name,f.type||inferMime(f.name));return true}catch(e){if(e.name==="AbortError")return false;throw e}}
function pickWithInput(){return new Promise(res=>{const inp=document.createElement("input");inp.type="file";inp.style.display="none";document.body.appendChild(inp);inp.addEventListener("change",async()=>{const f=inp.files[0];if(f){const b=await f.arrayBuffer();stageFile(new Uint8Array(b),f.name,f.type||inferMime(f.name))}document.body.removeChild(inp);res(!!f)});inp.addEventListener("cancel",()=>{document.body.removeChild(inp);res(false)});inp.click()})}
btnPick.addEventListener("click",async()=>{try{if(typeof window.showOpenFilePicker==="function"){await pickWithFSA()}else{await pickWithInput()}}catch(e){setStatus("error","Picker error: "+e.message)}});
dropZone.addEventListener("click",()=>btnPick.click());
dropZone.addEventListener("keydown",(e)=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();btnPick.click()}});
dropZone.addEventListener("dragenter",(e)=>{e.preventDefault();dropZone.classList.add("drag-over")});
dropZone.addEventListener("dragover",(e)=>{e.preventDefault();e.dataTransfer.dropEffect="copy";dropZone.classList.add("drag-over")});
dropZone.addEventListener("dragleave",()=>dropZone.classList.remove("drag-over"));
dropZone.addEventListener("drop",async(e)=>{e.preventDefault();dropZone.classList.remove("drag-over");const f=e.dataTransfer.files[0];if(!f)return;const b=await f.arrayBuffer();stageFile(new Uint8Array(b),f.name,f.type||inferMime(f.name))});
frame.addEventListener("load",()=>{if(!frame.src||frame.src==="about:blank")return;overlayMsg.textContent="Initializing…";setTimeout(()=>{if(!contentReady)showConverter("Converter loaded (try injecting your file)")},5000)});
frame.addEventListener("error",()=>{overlay.classList.add("gone");frameErr.classList.add("on");setStatus("error","Failed to load converter")});
btnRetry.addEventListener("click",()=>{frameErr.classList.remove("on");overlay.classList.remove("gone");contentReady=false;setStatus("loading","Loading p2r3 converter…");frame.src="https://p2r3.github.io/convert/"});
function showConverter(m){overlay.classList.add("gone");frame.classList.add("ready");setStatus("ok",m||"Converter ready — pick a file and click ⬇ Inject")}
window.addEventListener("message",(e)=>{if(!e.data)return;if(e.data.type==="P2R3_READY"){contentReady=true;showConverter()}else if(e.data.type==="P2R3_RESULT"){if(e.data.ok){setStatus("injected","✔ \""+e.data.fileName+"\" injected — select formats & convert!")}else{setStatus("error","Injection failed: "+(e.data.error??"unknown"))}btnInject.disabled=false}});
btnInject.addEventListener("click",()=>{if(!stagedFile){setStatus("error","No file selected.");return}btnInject.disabled=true;setStatus("loading","Injecting file…");frame.contentWindow.postMessage({type:"P2R3_INJECT_FILE",fileData:Array.from(stagedFile.fileData),fileName:stagedFile.fileName,fileType:stagedFile.fileType},"https://p2r3.github.io")});
